apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-core
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        component: core
    spec:
      containers:
      - image: grafana/grafana:4.2.0
        name: grafana-core
        imagePullPolicy: IfNotPresent
        # env:
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          # The following env variables set up basic auth twith the default admin user and admin password.
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
          # - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          #   value: Admin
          # does not really work, because of template variables in exported dashboards:
          # - name: GF_DASHBOARDS_JSON_ENABLED
          #   value: "true"
          - name: GF_SMTP_ENABLED
            value: "true"
          - name: GF_SMTP_FROM_ADDRESS
            value: "noreply+grafana@qwil.co"
          - name: GF_SMTP_HOST
            value: "smtp.sendgrid.net"
          - name: GF_SMTP_USER
            value: "apikey"
          - name: GF_SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-secret
                key: email-password
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
          # initialDelaySeconds: 30
          # timeoutSeconds: 1
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var
      - name: ssl-proxy
        env:
        - name: TARGET_SERVICE
          value: localhost:3000
        image: us.gcr.io/qwil-build/ssl-proxy:latest
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/secrets/
          name: certificates
          readOnly: true
        - mountPath: /etc/dhparam/
          name: dhparam
          readOnly: true
      volumes:
      - name: grafana-persistent-storage
        persistentVolumeClaim:
          claimName: grafana-storage
      - name: certificates
        secret:
          defaultMode: 420
          items:
          - key: tls.key
            path: proxykey
          - key: tls.crt
            path: proxycert
          secretName: star.builds.qwil.co
      - name: dhparam
        secret:
          defaultMode: 420
          items:
          - key: dhparam.pem
            path: dhparam
          secretName: dhparam
