apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: core
  annotations:
    qwil.co/dns-name: "grafana.builds.qwil.co"
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    protocol: TCP
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: grafana
    component: core
